name: Greeting from LAI Man Hin
on: push
jobs:
my-job:
name: My Job
runs-on: ubuntu-latest
steps:
- name: Print a greeting
env:
MY_VAR: Hi there! My name is
FIRST_NAME: LAI
MIDDLE_NAME: Man
LAST_NAME: Hin
run: |
echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
